import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'
import { ThemeProvider } from '@/components/theme-provider'
import Link from 'next/link'
import { ModeToggle } from '@/components/mode-toggle'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Poke-Finder',
  description: 'Generated by create next app',
}

 // Providers


export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <head>
        <link rel="icon" href="/favicon.ico"/>
      </head>
      <body className={inter.className}>
        <ThemeProvider attribute='class' defaultTheme='dark'>
        <main className="flex min-h-screen flex-col items-center p-24">
          <div className="z-10 max-w-5xl w-full items-center justify-between font-mono text-sm lg:flex">
            <Link href="/"><h2 className='text-2xl text-bold mb-5'>PokemonFinder</h2></Link>
            <ModeToggle/>
          </div>
        {children}
        </main>
        </ThemeProvider>
      </body>
    </html>
  )
}
